server:
  port: 8088
  servlet:
    context-path: /xxl-job-admin

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xiaobin-job?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 3000

  freemarker:
    suffix: .ftl
    settings:
      classic_compatible: true
      datetime_format: yyyy-MM-dd HH:mm:ss
      number_format: 0.##

# MyBatis Mapper XML (xxl-job-admin自带的Mapper)
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

xxl:
  job:
    accessToken:
