spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: xiaobin

jwt:
  secret: xiaobin-node-secret-key-for-jwt-token-generation-2026

netty:
  websocket:
    port: 9090

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    enabled: true
