spring:
  application:
    name: xiaobin-chat
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: xiaobin
        import-check:
          enabled: false
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: xiaobin
  config:
    import:
      - nacos:common-config.yaml?group=DEFAULT_GROUP&namespace=xiaobin
      - nacos:xiaobin-chat.yaml?group=DEFAULT_GROUP&namespace=xiaobin

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    enabled: true

server:
  port: 8084
