spring:
  application:
    name: xiaobin-job-executor
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: xiaobin
        import-check:
          enabled: false
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: xiaobin
  config:
    import:
      - nacos:common-config.yaml?group=DEFAULT_GROUP&namespace=xiaobin
      - nacos:xiaobin-job-executor.yaml?group=DEFAULT_GROUP&namespace=xiaobin

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8088/xxl-job-admin
    executor:
      appname: xiaobin-job
      port: 9999
      logpath: ./logs/xxl-job
    # 与 xiaobin-admin 调度中心的 accessToken 保持一致
    accessToken: default_token

server:
  port: 8085
